version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: adaptive_bot_db
    environment:
      POSTGRES_DB: adaptive_bot
      POSTGRES_USER: bot_user
      POSTGRES_PASSWORD: bot_password_2024
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bot_user -d adaptive_bot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  default:
    name: adaptive_bot_network