services:
  # Definicja pierwszego serwisu: serwer API z modelem
  api_service_eth:
    build: .
    command: python api_service_eth.py
    ports:
      - "8082:8082"
    env_file:
      - .env
    volumes:
      - .:/app

  # Definicja drugiego serwisu: bot tradingowy
  trading_bot_eth:
    build: .
    command: python trading_bot_eth.py
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - api_service_eth