services:

  bot-eth-syl:
    container_name: eth-syl
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env_sylwia
    volumes:
      # Mount only essential directories for trading
      - ./models:/app/models
      - ./logs:/app/logs
      - ./bot_state:/app/bot_state
    restart: unless-stopped
    command: >
      python main.py --run-bot
      --ticker ETHUSDT
      --timeframe 15m
      --helper-timeframes 1h 4h
      --prob-threshold 0.65
      --tsl-pct 0.01
      --tp-pct 0.02
      --trade-size 50.0
      --leverage 10 
      --partial-tp

