services:

  bot-syl-sol-dynamic-tp:
    container_name: syl-sol-dynamic-tp
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env_sylwia
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
      - ./bot_state:/app/bot_state
    restart: unless-stopped
    command: >
      python main.py --run-bot
      --version v1.1
      --ticker SOLUSDT
      --timeframe 15m
      --helper-timeframes 1h 4h 1D
      --prob-threshold 0.62
      --min-proba-diff 0.3
      --tsl-pct 0.014
      --tp-pct 0.02
      --trade-size 100.0
      --leverage 10
      --partial-tp

  bot-luk-sol-dynamic-tp:
    container_name: luk-sol-dynamic-tp
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env_luk
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
      - ./bot_state:/app/bot_state
    restart: unless-stopped
    command: >
      python main.py --run-bot
      --version v1.1
      --ticker SOLUSDT
      --timeframe 15m
      --helper-timeframes 1h 4h 1D
      --prob-threshold 0.62
      --min-proba-diff 0.3
      --tsl-pct 0.014
      --tp-pct 0.02
      --trade-size 300.0
      --leverage 10
      --partial-tp
      --hedge-mode
